name: Bump, Tag & Publish with pnpm

on:
  push:
    branches: [main]

jobs:
  bump-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Verify template directory
        run: |
          if [ ! -d "template/authjs-prisma-shadcn-protecteed" ]; then
            echo "❌ Directory template/authjs-prisma-shadcn-protecteed does not exist!"
            exit 1
          fi
          echo "✅ Directory template/authjs-prisma-shadcn-protecteed exists."

      - name: List files
        run: ls -R template

      - name: Prepare template
        run: pnpm prepare-template

      - name: Bump version
        run: |
          pnpm bump:patch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "chore: bump version to v$VERSION"
          git tag v$VERSION
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --no-git-checks
